// Login
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

// Categories
export const CATEGORY_SUCCESSFULL = 'CATEGORY_SUCCESSFULL';
export const CATEGORY_FAILUTE = 'CATEGORY_FAILUTE';
