export const quizTypes = {
  GET_CATEGORIES: "GET_CATEGORIES",
  CATEGORIES_ERROR: "CATEGORIES_ERROR",
  ADD_QUIZ: "ADD_QUIZ",
  GET_WALLET_TRANSACTIONS: "GET_WALLET_TRANSACTIONS",
  SET_USER: "SET_USER",
};

export const authTypes = {
  LOGIN_START: "LOGIN_START",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  SET_USER: "SET_USER",
};
